@echo off
chcp 65001 >nul
setlocal
cd /d "%~dp0"

rem ---------------------------------------------------------------------------
rem  Traiectus Server - one-click start (Phase 3 integration)
rem
rem  * shows a live console window
rem  * writes the same output to build\server-live.log
rem  * stop with Ctrl+C in this window, or just close the window
rem
rem  ASCII-only on purpose (cmd.exe reads .bat with the local OEM code page).
rem ---------------------------------------------------------------------------

set "EXE=%~dp0build\Traiectus-Server.exe"
set "LOG=%~dp0build\server-live.log"
rem  --device is OPTIONAL: leave DEV empty and the server auto-detects the mouse
rem  you are actually using (watch for a "DEVICE PICK ..." line in the log).
rem  To pin one specific mouse, put its id here -- run the server with --list
rem  to see the ids, e.g.  set "DEV=VID_xxxx&PID_xxxx&MI_00"
set "DEV="
set "EXTRA="
set "DEVARG="
if defined DEV set DEVARG=--device "%DEV%"

rem  -- handshake: none to configure -------------------------------------------
rem  There is NO token to set.  The password is generated by pairing and stored
rem  in paired.json; the first time a Mac connects, a confirm box appears on
rem  Windows -- click Allow.  (The --token option was removed on 2026-10-01.)
rem
rem  Optional: "start-server.bat verbose" logs every outgoing protocol line too.
if /i "%~1"=="verbose" (
    set "EXTRA=--verbose"
    set "LOG=%~dp0build\server-verbose.log"
)

rem  Optional: "start-server.bat mac" starts already in Mac mode (Ctrl+Alt+M toggles anyway).
if /i "%~1"=="mac" (
    set "EXTRA=--start-in-mac-mode"
)

if not exist "%EXE%" (
    echo [ERROR] not found: %EXE%
    echo         Run build-mingw.bat first.
    pause
    exit /b 1
)

echo =====================================================
echo  Traiectus Server
if defined DEV (echo   device : pinned via DEV in this file) else (echo   device : auto-detect)
echo   auth   : pairing (no token to configure)
echo   port   : 45789
echo   log    : %LOG%
echo   args   : %EXTRA%
echo   switch : Ctrl+Alt+M   (Windows ^<-^> Mac)
echo   default: Windows mode = nothing forwarded, Windows stays 100%% native
echo   stop   : Ctrl+C here, or close this window
echo =====================================================
echo.

rem  Set the console output encoding first, otherwise the UTF-8 output of the
rem  server gets decoded as the local code page and the log fills with mojibake.
powershell -NoProfile -ExecutionPolicy Bypass -Command "[Console]::OutputEncoding = [System.Text.Encoding]::UTF8; & '%EXE%' %DEVARG% %EXTRA% 2>&1 | Tee-Object -FilePath '%LOG%'"

echo.
echo [exited] the output above was also saved to:
echo          %LOG%
pause
